# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gnw', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_Learning_Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.Enrollment')),
                ('lesson_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnw.Lesson_Material')),
            ],
        ),
    ]
