# Generated by Django 3.2.5 on 2021-08-11 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_completed_lessons_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed_lessons',
            name='taken',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
