# Generated by Django 3.2.5 on 2021-09-16 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_completed_lessons_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_lessons',
            name='taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
