# Generated by Django 3.2.5 on 2021-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=25)),
                ('token_hex_str', models.CharField(max_length=32)),
                ('created', models.DateTimeField()),
                ('sms_sent', models.PositiveSmallIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SMS_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=7)),
                ('created', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('tries', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=25)),
                ('session_key', models.CharField(max_length=40)),
                ('token_hex_str', models.CharField(max_length=32)),
                ('created', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
