# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=7)),
                ('last_update', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
