# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20180410_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms_code',
            name='tries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
