# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_sms_code_tries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=25)),
                ('token_hex_str', models.CharField(max_length=32)),
                ('created', models.DateTimeField()),
                ('sms_sent', models.PositiveSmallIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
