# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200)),
                ('lesson_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.PositiveIntegerField()),
                ('material_title', models.CharField(blank=True, max_length=50)),
                ('file_name', models.CharField(default='#', max_length=200)),
                ('random_slug', models.CharField(max_length=6, unique=True)),
                ('material_type', models.CharField(choices=[('VD', 'Video'), ('DL', 'Download')], default='VD', max_length=2)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnw.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=200)),
                ('unit_number', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnw.Course')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnw.Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set([('course', 'unit_number'), ('course', 'unit_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='lesson_material',
            unique_together=set([('lesson', 'material_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set([('unit', 'lesson_name'), ('unit', 'lesson_number')]),
        ),
    ]
