# Generated by Django 3.2.5 on 2021-07-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=200)),
                ('unit_number', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnw.course')),
            ],
            options={
                'unique_together': {('course', 'unit_name'), ('course', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200)),
                ('lesson_number', models.PositiveIntegerField()),
                ('random_slug', models.CharField(max_length=6, unique=True)),
                ('lesson_type', models.CharField(choices=[('VIDEO', 'Video'), ('QUIZ', 'Quiz')], max_length=25)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnw.unit')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gnw.video')),
            ],
            options={
                'unique_together': {('unit', 'lesson_number'), ('unit', 'lesson_name')},
            },
        ),
    ]
