# Generated by Django 3.2.5 on 2021-07-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_time', models.TimeField(help_text='format: <em>1:29</em>')),
                ('resume_time', models.TimeField(help_text='format: <em>1:29</em>')),
                ('number_of_chocies', models.PositiveIntegerField(choices=[(2, 'Two'), (3, 'Three'), (4, 'Four')])),
                ('correct_choice', models.PositiveIntegerField(choices=[(1, 'Choice One'), (2, 'Choice Two'), (3, 'Choice Three'), (4, 'Choice Four')])),
                ('branching_video', models.BooleanField(default=False)),
                ('branch_1_start_time', models.TimeField(blank=True, help_text='format: <em>1:29</em>', null=True)),
                ('branch_1_end_time', models.TimeField(blank=True, help_text='format: <em>1:29</em>', null=True)),
                ('branch_2_start_time', models.TimeField(blank=True, help_text='format: <em>1:29</em>', null=True)),
                ('branch_2_end_time', models.TimeField(blank=True, help_text='format: <em>1:29</em>', null=True)),
                ('branch_3_start_time', models.TimeField(blank=True, help_text='format: <em>1:29</em>', null=True)),
                ('branch_3_end_time', models.TimeField(blank=True, help_text='format: <em>1:29</em>', null=True)),
                ('branch_4_start_time', models.TimeField(blank=True, help_text='format: <em>1:29</em>', null=True)),
                ('branch_4_end_time', models.TimeField(blank=True, help_text='format: <em>1:29</em>', null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnw.video')),
            ],
        ),
    ]
