# Generated by Django 3.2.5 on 2021-07-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0002_video_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_question',
            old_name='number_of_chocies',
            new_name='number_of_choices',
        ),
    ]
