# Generated by Django 3.2.5 on 2021-07-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0003_rename_number_of_chocies_video_question_number_of_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_question',
            old_name='branch_1_end_time',
            new_name='end_time_branch_1',
        ),
        migrations.RenameField(
            model_name='video_question',
            old_name='branch_1_start_time',
            new_name='start_time_branch_1',
        ),
        migrations.RenameField(
            model_name='video_question',
            old_name='branch_2_end_time',
            new_name='end_time_branch_2',
        ),
        migrations.RenameField(
            model_name='video_question',
            old_name='branch_2_start_time',
            new_name='start_time_branch_2',
        ),
        migrations.RenameField(
            model_name='video_question',
            old_name='branch_3_end_time',
            new_name='end_time_branch_3',
        ),
        migrations.RenameField(
            model_name='video_question',
            old_name='branch_3_start_time',
            new_name='start_time_branch_3',
        ),
        migrations.RenameField(
            model_name='video_question',
            old_name='branch_4_end_time',
            new_name='end_time_branch_4',
        ),
        migrations.RenameField(
            model_name='video_question',
            old_name='branch_4_start_time',
            new_name='start_time_branch_4',
        ),
    ]
