# Generated by Django 3.2.5 on 2021-07-21 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0004_auto_20210713_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
                ('properties', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video_question',
            name='end_time_branch_1',
            field=models.TimeField(blank=True, help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>', null=True),
        ),
        migrations.AlterField(
            model_name='video_question',
            name='end_time_branch_2',
            field=models.TimeField(blank=True, help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>', null=True),
        ),
        migrations.AlterField(
            model_name='video_question',
            name='end_time_branch_3',
            field=models.TimeField(blank=True, help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>', null=True),
        ),
        migrations.AlterField(
            model_name='video_question',
            name='end_time_branch_4',
            field=models.TimeField(blank=True, help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>', null=True),
        ),
        migrations.AlterField(
            model_name='video_question',
            name='pause_time',
            field=models.TimeField(help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>'),
        ),
        migrations.AlterField(
            model_name='video_question',
            name='resume_time',
            field=models.TimeField(help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>'),
        ),
        migrations.AlterField(
            model_name='video_question',
            name='start_time_branch_1',
            field=models.TimeField(blank=True, help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>', null=True),
        ),
        migrations.AlterField(
            model_name='video_question',
            name='start_time_branch_2',
            field=models.TimeField(blank=True, help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>', null=True),
        ),
        migrations.AlterField(
            model_name='video_question',
            name='start_time_branch_3',
            field=models.TimeField(blank=True, help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>', null=True),
        ),
        migrations.AlterField(
            model_name='video_question',
            name='start_time_branch_4',
            field=models.TimeField(blank=True, help_text='format: <em>HH:MM:SS e.g. 00:01:29</em>', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gnw.quiz'),
        ),
    ]
