# Generated by Django 3.2.5 on 2021-07-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0005_auto_20210721_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(max_length=500)),
                ('type_of_options', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], default='TEXT', max_length=20)),
                ('media_file_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('media_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_choice', models.PositiveIntegerField(choices=[(1, 'Choice One'), (2, 'Choice Two'), (3, 'Choice Three'), (4, 'Choice Four')])),
                ('content_option_1', models.CharField(max_length=200)),
                ('content_option_2', models.CharField(max_length=200)),
                ('content_option_3', models.CharField(max_length=200)),
                ('content_option_4', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='mc_question',
            field=models.ManyToManyField(to='gnw.Quiz_Question'),
        ),
    ]
