# Generated by Django 3.2.5 on 2021-07-31 03:50

from django.db import migrations, models
import gnw.models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0009_alter_quiz_question_media_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='random_slug',
            field=models.CharField(default=gnw.models.Lesson.random_id_generator, max_length=6, unique=True),
        ),
    ]
