# Generated by Django 3.2.5 on 2021-07-31 12:58

from django.db import migrations, models
import gnw.models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0013_auto_20210731_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.PositiveIntegerField(default=gnw.models.Lesson.generate_lesson_order_number, help_text='Use default value unless re-ordering lessons', unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.PositiveIntegerField(default=gnw.models.Unit.generate_unit_order_number, help_text='Use default value unless re-ordering units', unique=True),
        ),
    ]
