# Generated by Django 3.2.5 on 2021-08-01 03:45

from django.db import migrations, models
import gnw.models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0014_auto_20210731_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank unless re-ordering lessons'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.PositiveIntegerField(default=gnw.models.Unit.generate_unit_order_number, help_text='Use default value unless re-ordering units'),
        ),
    ]
