# Generated by Django 3.2.5 on 2021-08-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0015_auto_20210801_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank unless re-ordering units'),
        ),
    ]
