# Generated by Django 3.2.5 on 2021-08-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0016_alter_unit_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.PositiveIntegerField(blank=True, help_text='Do not change unless re-ordering lessons'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.PositiveIntegerField(blank=True, help_text='Do not change unless re-ordering units'),
        ),
    ]
