# Generated by Django 3.2.5 on 2021-08-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0017_auto_20210802_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
