# Generated by Django 3.2.5 on 2021-08-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0018_auto_20210803_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_unlocked',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_public',
        ),
    ]
