# Generated by Django 3.2.5 on 2021-08-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0021_alter_course_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video_Question',
        ),
    ]
