# Generated by Django 3.2.5 on 2021-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0022_delete_video_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='correct_choice',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='media_file_name',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='media_file_type',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='question_title',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='type_of_options',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='lesson',
            field=models.ManyToManyField(to='gnw.Lesson'),
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='question_name',
            field=models.CharField(default='Temp name', help_text='This is what comes up in database search results. It does not appear in the actual quiz question.', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
