# Generated by Django 3.2.5 on 2021-09-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0024_auto_20210828_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='photo',
        ),
        migrations.AddField(
            model_name='assignment',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
