# Generated by Django 3.2.5 on 2021-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0027_auto_20210911_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='image',
        ),
        migrations.AddField(
            model_name='assignment',
            name='image1',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
