# Generated by Django 3.2.5 on 2021-09-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0029_auto_20210912_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='image8',
        ),
    ]
