# Generated by Django 3.2.5 on 2021-09-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0030_auto_20210912_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submitted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
