# Generated by Django 3.2.5 on 2021-09-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnw', '0032_assignment_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='image2',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
