# Generated by Django 3.2.5 on 2021-09-13 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gnw', '0033_alter_assignment_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gnw.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.customuser'),
            preserve_default=False,
        ),
    ]
