# Generated by Django 3.2.5 on 2021-09-16 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gnw', '0036_assignment_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='graded_time',
            field=models.DateTimeField(blank=True, help_text='Leave blank to use system default', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='properties',
            field=models.JSONField(blank=True, help_text='Leave blank for now', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submitted_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Leave blank to use system default'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
