# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='staff_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='student_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
