# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180502_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_birth_date',
            field=models.DateField(blank=True, help_text='格式: 2010-08-31', null=True),
        ),
    ]
