# Generated by Django 3.2.5 on 2021-07-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210729_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
