# Generated by Django 3.2.5 on 2021-08-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_student_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
