# Generated by Django 3.2.5 on 2021-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='require_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
