# Generated by Django 3.1.7 on 2021-03-09 12:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
#import partial_index


class Migration(migrations.Migration):

    #replaces = [('enrollment', '0001_squashed_0003_auto_20180501_1155'), ('enrollment', '0004_auto_20180501_1516'), ('enrollment', '0005_auto_20180501_1547'), ('enrollment', '0006_auto_20180501_1557'), ('enrollment', '0007_auto_20210309_1719')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gnw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=datetime.date.today)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gnw.course')),
                ('enrollment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.enrollment_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': set(),
            },
        ),
        #migrations.AddIndex(
        #    model_name='enrollment',
        #    index=partial_index.PartialIndex(fields=['user', 'course'], name='enrollment__user_id_5c3844_partial', unique=True, where='is_current', where_postgresql='', where_sqlite=''),
        #),
        migrations.AlterField(
            model_name='enrollment',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        #migrations.RemoveIndex(
        #    model_name='enrollment',
        #    name='enrollment__user_id_5c3844_partial',
        #),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(is_current=True), fields=('user', 'course'), name='unique_user_enrolled_in_current_course'),
        ),
    ]
