# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20180328_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set([]),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=partial_index.PartialIndex(fields=['user', 'course'], name='enrollment__user_id_5c3844_partial', unique=True, where='is_current', where_postgresql='', where_sqlite=''),
        ),
    ]
