# Generated by Django 3.2.5 on 2021-09-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_auto_20210927_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_new_order',
            name='failure_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='process_new_order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
